### ISSUE TITLE
Failed installing plugin on backstage 1.19.0

### ISSUE THREAD

**Issue by kratosmat** [kubevela-contrib/backstage-plugin-kubevela#5]
Hello,
I am trying to install the plugin for kubevela on backstage 1.19.0 but I am facing the following errors:

~/Developments/CPF/backstage/backstage-idp$ yarn tsc
yarn run v1.22.19
$ tsc
packages/app/src/components/Root/Root.tsx:29:10 - error TS2305: Module '"@oamdev/backstage-plugin-velaux"' has no exported member 'VelaLogo'.

29 import { VelaLogo } from '@oamdev/backstage-plugin-velaux';
            ~~~~~~~~

packages/backend/src/plugins/catalog.ts:12:47 - error TS2345: Argument of type 'UrlReaderService' is not assignable to parameter of type 'UrlReader'.
  Property 'read' is missing in type 'UrlReaderService' but required in type 'UrlReader'.

12   const vela = new VelaProvider('production', env.reader, env.config);
                                                 ~~~~~~~~~~

  node_modules/@oamdev/plugin-kubevela-backend/node_modules/@backstage/backend-common/dist/index.d.ts:1587:5
    1587     read(url: string): Promise<Buffer>;
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'read' is declared here.


Found 2 errors in 2 files.

Errors  Files
     1  packages/app/src/components/Root/Root.tsx:29
     1  packages/backend/src/plugins/catalog.ts:12
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.



Could you please help me?
Thanks a lot,
Matteo.

**Comment by FrancescoGraziano** [comment]
Hello Matteo,
I got the same issue here. Did you fixed it somehow?
Regards
Francesco

**Comment by Renz2018** [comment]
[MR ](https://github.com/kubevela-contrib/backstage-plugin-kubevela/pull/7/files)merged， but npm release is out of date.
@FrancescoGraziano @kratosmat

**Comment by kratosmat** [comment]
Thanks @FrancescoGraziano to fix the issue

**Comment by wonderflow** [comment]
Thanks @FrancescoGraziano @kratosmat  https://github.com/FrancescoGraziano/backstage-plugin-kubevela/pull/1
